# Generated by Django 3.2.10 on 2021-12-26 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology_dbms', '0002_directory_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
